timeout: 30000
enableInlineShortcodes: true

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: false

  twitter:
    disabled: false
    enableDNT: true
    simple: true
    disableInlineCSS: true

  instagram:
    disabled: false
    simple: false

  youtube:
    disabled: false
    privacyEnhanced: true
